import{i as d,S as u}from"./assets/vendor-0fc460d7.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const r of t.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&s(r)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const c=document.querySelector(".form"),p=document.querySelector(".input"),l=document.querySelector(".gallery"),n=document.querySelector(".loader");function f(a){a.preventDefault(),l.innerHTML="",n.classList.remove("visually-hidden");const o=p.value.trim();if(o===""){n.classList.add("visually-hidden");return}const i=new URLSearchParams({key:"16437496-6d56e114a2cb1088922bcb1d6",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:21});fetch(`https://pixabay.com/api/?${i}`).then(s=>s.json()).then(s=>{if(s.hits.length===0)n.classList.add("visually-hidden"),d.error({position:"topRight",messageColor:"white",backgroundColor:"red",message:"Sorry, there are no images matching your search query. Please try again!"});else{const e=s.hits.map(r=>`<li><a class="gallery-link" href=${r.largeImageURL}><img src="${r.webformatURL}" alt="${r.tags}">
            
            <div>
            <p><span>Likes</span>${r.likes}</p>
            <p><span>Views</span>${r.views}</p>
            <p><span>Comments</span>${r.comments}</p>
            <p><span>Downloads</span>${r.downloads}</p>
            </div>
</a>
            </li>`).join("");n.classList.add("visually-hidden"),l.insertAdjacentHTML("beforeend",e);let t=new u(".gallery a",{captionsData:"alt",captionDelay:250});t.refresh(),t.on("show.simplelightbox",function(){})}}).catch(s=>console.log(s)),c.reset()}c.addEventListener("submit",f);
//# sourceMappingURL=commonHelpers.js.map
